from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
STATE_FILE = PROJECT_ROOT / "state.json"
ENV_FILE = PROJECT_ROOT / ".env"
RUNTIME_CONFIG_FILE = DATA_DIR / "runtime_config.json"
PNL_LEDGER_FILE = DATA_DIR / "pnl_ledger.jsonl"
BLACKLIST_FILE = DATA_DIR / "blacklist_day.json"
PRICE_SAMPLES_DIR = DATA_DIR / "price_samples"
UI_DIST_DIR = PROJECT_ROOT / "ui" / "dist"

TIMEZONE = "Asia/Jerusalem"
REPORT_HOURS = (10, 13, 16, 19)
SCAN_INTERVAL_SECONDS = 20
SELL_BELOW_MIN_COOLDOWN_SEC = 86400

BUY_MIN_THRESHOLD = 0.55
BUY_MAX_THRESHOLD = 0.70
STOP_LOSS_THRESHOLD = 0.44
TAKE_PROFIT_THRESHOLD = 0.98
DEFAULT_ORDER_SIZE = 10.0
MAX_TRADE_FRACTION_OF_CASH = 0.90
MAX_BUY_NOTIONAL_USD = 5.0
MIN_ORDER_NOTIONAL_USD = 2.0
# never allocate buys from this portion of free cash (runtime + UI override)
CASH_RESERVE_USD = 5.0

MIN_LEAD_OVER_RUNNER_UP = 0.07
ENABLE_COMPETITION_FILTER = True

ENABLE_MOMENTUM = False
MOMENTUM_WINDOW_MIN = 10
MOMENTUM_RISE = 0.25
MOMENTUM_MIN_PRICE = 0.40
MOMENTUM_MAX_ENTRY = 0.65
MOMENTUM_PEER_DROP = 0.10
PRICE_SAMPLE_RETENTION_DAYS = 7
PRICE_SAMPLE_MAX_ENTRIES_PER_MARKET = 30

CHURN_MAX_STOP_CYCLES = 1
CHURN_COOLDOWN_SEC = 1200

YES_LABEL = "YES"
STATUS_CLOSED = frozenset({"closed", "claimable", "resolved"})
DUST_SHARES_EPS = 1e-6

TERM_RESET = "\033[0m"
TERM_BOLD = "\033[1m"
TERM_DIM = "\033[2m"
TERM_GREEN = "\033[32m"
TERM_RED = "\033[31m"
TERM_YELLOW = "\033[33m"
TERM_CYAN = "\033[36m"
